### ISSUE TITLE
Pixy Setup

### ISSUE THREAD

**Issue by nicklesimba** [RoboEagles4828/2017Robot#10]
We are messing with the pixy. 
--
- So all Jackson did to get better detection is reset settings to default in pixymon, and then: 
increase signature 1's range to 7 or higher, and lowered camera brightness to 26. 
- exposure: 52738
- white balance: 8017984

This is being labeled as an issue because setup is not close to finished.

**Comment by P1n3appl3** [comment]
### Thanks for getting it set up, and for future reference: 
1. Don't write important reference info like those steps here, put them in the wiki, code comments, or readme depending on what it is. For those I made a [page on the wiki].(https://github.com/RoboEagles4828/2017Robot/wiki/Pixy)
2. Don't create an issue unless there is a concrete change that you want/need made. For something like this you could write a note in [the project](https://github.com/orgs/RoboEagles4828/projects/1) instead.
