### ISSUE TITLE
Readme buttons broken

### ISSUE THREAD

**Issue by P1n3appl3** [RoboEagles4828/2017Robot#13]
The "Code Climate" and "Code Coverage" buttons don't seem to be functioning, could someone look into it pls

**Comment by CheezBallzPi** [comment]
Try merging develop into master next meeting, once you test your code. That should fix.

**Comment by CheezBallzPi** [comment]
> could someone look into it pls

*Stares into abyss...* 
Okay.

**Comment by CheezBallzPi** [comment]
Fixed in #25
