### ISSUE TITLE
Auton routines

### ISSUE THREAD

**Issue by P1n3appl3** [RoboEagles4828/2017Robot#20]
I'm trying to get a complete list of potential auton routines so we know what we may have to write in the future. This doesn't mean that all of these will come to fruition but I just want an exhaustive list of possibilities. Right now I have these (in order of difficulty/likelihood of having to write them):

1. From a set position on the alliance wall, place a gear on the nearest lift
2. From **any** position on the alliance wall, place a gear on the nearest lift
3. From a set position on the alliance wall, fire starting fuel into the low or high goal
3. From a set position on the alliance wall place a gear on the lift nearest to the boiler, move to the boiler and fire starting fuel into the (low or high, i dont think we've made a final decision yet) goal
4. From **any** position on the alliance wall, place a gear on a side lift, then move towards and trigger a side-field hopper
5. From a set position on the alliance wall, move to the hopper near the boiler, trigger it in such a manner as to catch the balls that fall from it, then fire as many as possible into the high goal (it is unclear whether we would want to move closer to the boiler first at this time.

Keep in mind that any auton involving the boiler will have to be implemented differently based on which alliance you're on. With that in mind were there any auton routines brainstormed that I'm missing?

**Comment by CheezBallzPi** [comment]
Be able to shoot into the goal from **any** position on the alliance wall
