### ISSUE TITLE
Cannot resolve symbol "AHRS"

### ISSUE THREAD

**Issue by CheezBallzPi** [RoboEagles4828/2017Robot#26]
I was able to pull the library from git, but IntelliJ is not able to recognize it.

Problem found in Robot.java, line 20.

**Comment by P1n3appl3** [comment]
Try building the program it should still work, it's an issue with IDEA's handling of gradle dependencies as opposed to an actual issue with the code. Opening the gradle menu and refreshing all gradle projects fixed it for me, but ill look into whether doing `gradlew resolveNativeDeps` works as well.

**Comment by CheezBallzPi** [comment]
Didn't work. I'm missing CANTalons from CTRE now too.
