### ISSUE TITLE
On Formatting and CodeClimate

### ISSUE THREAD

**Issue by CheezBallzPi** [RoboEagles4828/2017Robot#38]
If you didn't know already, CodeClimate is a service that uses algorithms to check if your code has formatting errors or bad practices.

According to our CodeClimate page, we have close to ***100 issues***. [Link](https://codeclimate.com/github/RoboEagles4828/2017Robot/issues)

All of these changes should be easy fixes, but I'm too lazy to go fix them one by one. I would appreciate some help.

These changes should be made on the branch `hotfix/issues`. Make sure to `git fetch` before making a new branch.

**Comment by alebcay** [comment]
I've started on it. I assume I've made `hotfix/issues` branch off of `master`? Or should I branch off of `develop`?

**Comment by CheezBallzPi** [comment]
Branch off develop.

**Comment by alebcay** [comment]
Rebasing now.

**Comment by CheezBallzPi** [comment]
For future reference, all branches branch from develop.

**Comment by alebcay** [comment]
All clean now. Keep an eye on the CodeClimate build for each PR to avoid introducing new problems.
