### ISSUE TITLE
./gradlew: Permission denied

### ISSUE THREAD

**Issue by CheezBallzPi** [RoboEagles4828/2017Robot#4]
It's still happening. Someone use chmod or something to fix? I don't have linux on hand right now. 
@alebcay @P1n3appl3

**Comment by alebcay** [comment]
Are you trying to run from Windows shell? I just did a clean clone and have no problems.

**Comment by CheezBallzPi** [comment]
Can you `chmod` the `gradlew.bat` file also? Travis uses linux to run tests.

**Comment by alebcay** [comment]
I'm not actually sure how to add execute permissions to the `gradlew.bat` file. Best to do it from Windows, which actually executes/uses the file.
